name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bandit Security Scan
      uses: tj-actions/bandit@v3
      with:
        options: "-r ."

    - name: Run Basic Test (Flask App)
      run: |
        echo "from app import app; client = app.test_client(); assert client.get('/login').status_code == 200" > test_login.py
        python test_login.py
